build:
    image: rust:$$RUST_VERSION
    commands:
        - cargo test
        - cargo build --release

matrix:
  RUST_VERSION:
    - '1.5'
    - '1.6'
    - '1.7'
    - '1.8'
    - '1.9'
    - '1.10'
    - 'stable'
