language: minimal

services:
  - docker

before_install:
    - docker build -t rooster -f Dockerfile.alpine .

    # unit tests
    - docker run --user root --rm --entrypoint /bin/sh rooster -c 'cargo test'

    # integration tests
    - ./integration-tests/test-command-add.sh
    - ./integration-tests/test-command-change.sh
    - ./integration-tests/test-command-delete.sh
    - ./integration-tests/test-command-export.sh
    - ./integration-tests/test-command-generate.sh
    - ./integration-tests/test-command-get.sh
    - ./integration-tests/test-command-list.sh
    - ./integration-tests/test-command-regenerate.sh
    - ./integration-tests/test-command-rename.sh
    - ./integration-tests/test-command-set-master-password.sh
    - ./integration-tests/test-command-transfer.sh
    - ./integration-tests/test-command-uninstall.sh
    - ./integration-tests/test-command-weak.sh
    - ./integration-tests/test-corruption.sh
    - ./integration-tests/test-password-retry-nok.sh
    - ./integration-tests/test-password-retry-ok.sh
    - ./integration-tests/test-setup.sh

script:
    - true
