[package]
name = "rooster"
version = "2.0.0"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]
license = "Apache-2.0"
repository = "https://github.com/conradkleinespel/rooster"
homepage = "https://github.com/conradkleinespel/rooster"
keywords = ["password", "security"]
description = "A simple password manager for geeks"

[dependencies]
rust-crypto = "0.2"
rustc-serialize = "0.3"
rand = "0.3"
libc = "0.1"
rpassword = "0.1"
getopts = "0.2"
byteorder = "0.3"
hyper = "0.7"
chrono = "0.2"
