[package]
name = "peevee-cli"
version = "0.0.1"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]

[dependencies]
rust-crypto = "*"
rustc-serialize = "*"
rand = "*"

[dependencies.rpassword]
# until rpassword is updated on crates.io, use the path
path = "../rpassword"
