[package]
name = "rooster"
version = "2.5.0"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]
license = "Apache-2.0"
repository = "https://github.com/conradkleinespel/rooster"
homepage = "https://github.com/conradkleinespel/rooster"
keywords = ["password", "security"]
description = "A simple password manager for geeks"

[dependencies]
rust-crypto = "0.2"
rustc-serialize = "0.3"
rand = "0.3"
libc = "0.2"
rpassword = "0.4"
getopts = "0.2"
byteorder = "1.0"
clipboard = "0.3"
quale = "1.0"
unix-daemonize = "0.1" # only needed for linux

[[bin]]
name = "rooster"
path = "src/main-rooster.rs"

[[bin]]
name = "rooster-clipboard"
path = "src/main-rooster-clipboard.rs"
