[package]
name = "rooster"
version = "0.0.1"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]

[dependencies]
rust-crypto = "*"
rustc-serialize = "*"
rand = "*"
libc = "*"
rpassword = "*"
getopts = "*"
